name: 'medallion_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medallion_project:

    staging:
      +schema: BINDARA_DEV_SILVER
      +materialized: view

    marts:
      +schema: BINDARA_DEV_GOLD
      +materialized: table
